cleanupUnusedCatalogs: true
linkWorkspacePackages: true
preferWorkspacePackages: true

packageExtensions:
  '@codspeed/vitest-plugin@*':
    peerDependenciesMeta:
      vite:
        optional: true

packages:
  - 'benchmarks/*'
  - 'packages/*'
