cleanupUnusedCatalogs: true
linkWorkspacePackages: true
preferWorkspacePackages: true
blockExoticSubdeps: true
trustPolicy: 'no-downgrade'

overrides:
  pino: 10.3.1
  undici-types: 8.4.1

packageExtensions:
  '@codspeed/vitest-plugin@*':
    peerDependenciesMeta:
      vite:
        optional: true

packages:
  - 'benchmarks/*'
  - 'packages/*'

allowBuilds:
  core-js: false
  esbuild: true
  nx: false
  unrs-resolver: false
