import { execSync } from 'node:child_process'
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from 'node:fs'
import { join } from 'node:path'
import { findSkillFiles, parseFrontmatter } from './utils.js'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface SetupResult {
  workflows: string[]
  skipped: string[]
  shim: string | null
  labels: string[]
}

interface TemplateVars {
  PACKAGE_NAME: string
  REPO: string
  DOCS_PATH: string
  SRC_PATH: string
}

// ---------------------------------------------------------------------------
// Variable detection from package.json
// ---------------------------------------------------------------------------

function detectVars(root: string): TemplateVars {
  const pkgPath = join(root, 'package.json')
  let pkgJson: Record<string, unknown> = {}
  try {
    pkgJson = JSON.parse(readFileSync(pkgPath, 'utf8'))
  } catch {
    /* fallback to defaults */
  }

  const name = typeof pkgJson.name === 'string' ? pkgJson.name : 'unknown'
  const intent = pkgJson.intent as Record<string, unknown> | undefined

  const repo =
    typeof intent?.repo === 'string'
      ? intent.repo
      : name.replace(/^@/, '').replace(/\//, '/')

  const docs = typeof intent?.docs === 'string' ? intent.docs : 'docs/'

  // Best-guess src path from common monorepo patterns
  const shortName = name.replace(/^@[^/]+\//, '')
  let srcPath = `packages/${shortName}/src/**`
  if (existsSync(join(root, 'src'))) {
    srcPath = 'src/**'
  }

  return {
    PACKAGE_NAME: name,
    REPO: repo,
    DOCS_PATH: docs.endsWith('**') ? docs : docs.replace(/\/$/, '') + '/**',
    SRC_PATH: srcPath,
  }
}

// ---------------------------------------------------------------------------
// Template variable substitution
// ---------------------------------------------------------------------------

function applyVars(content: string, vars: TemplateVars): string {
  return content
    .replace(/\{\{PACKAGE_NAME\}\}/g, vars.PACKAGE_NAME)
    .replace(/\{\{REPO\}\}/g, vars.REPO)
    .replace(/\{\{DOCS_PATH\}\}/g, vars.DOCS_PATH)
    .replace(/\{\{SRC_PATH\}\}/g, vars.SRC_PATH)
}

// ---------------------------------------------------------------------------
// Copy helpers
// ---------------------------------------------------------------------------

function copyTemplates(
  srcDir: string,
  destDir: string,
  vars: TemplateVars,
): { copied: string[]; skipped: string[] } {
  const copied: string[] = []
  const skipped: string[] = []

  if (!existsSync(srcDir)) return { copied, skipped }

  mkdirSync(destDir, { recursive: true })

  for (const entry of readdirSync(srcDir)) {
    const srcPath = join(srcDir, entry)
    const destPath = join(destDir, entry)

    if (existsSync(destPath)) {
      skipped.push(destPath)
      continue
    }

    const content = readFileSync(srcPath, 'utf8')
    const substituted = applyVars(content, vars)
    writeFileSync(destPath, substituted)
    copied.push(destPath)
  }

  return { copied, skipped }
}

// ---------------------------------------------------------------------------
// Shim generation
// ---------------------------------------------------------------------------

function getShimContent(ext: string): string {
  return `#!/usr/bin/env node
// Auto-generated by @tanstack/intent setup
// Exposes the intent end-user CLI for consumers of this library.
// Commit this file, then add to your package.json:
//   "bin": { "intent": "./bin/intent.${ext}" }
await import('@tanstack/intent/intent-library')
`
}

function generateShim(root: string, result: SetupResult): void {
  // Check if either extension already exists
  const shimJs = join(root, 'bin', 'intent.js')
  const shimMjs = join(root, 'bin', 'intent.mjs')

  if (existsSync(shimJs) || existsSync(shimMjs)) {
    result.skipped.push(existsSync(shimJs) ? shimJs : shimMjs)
    return
  }

  // Use .js if package has "type": "module", otherwise .mjs
  let ext = 'mjs'
  const pkgPath = join(root, 'package.json')
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
    if (pkg.type === 'module') ext = 'js'
  } catch {
    // default to .mjs
  }

  const shimPath = join(root, 'bin', `intent.${ext}`)
  mkdirSync(join(root, 'bin'), { recursive: true })
  writeFileSync(shimPath, getShimContent(ext))
  result.shim = shimPath
}

// ---------------------------------------------------------------------------
// Label creation
// ---------------------------------------------------------------------------

function createSkillLabels(root: string, repo: string, result: SetupResult): void {
  const skillsDir = join(root, 'skills')
  if (!existsSync(skillsDir)) return

  const skillFiles = findSkillFiles(skillsDir)
  for (const filePath of skillFiles) {
    const fm = parseFrontmatter(filePath)
    const name = typeof fm?.name === 'string' ? fm.name : null
    if (!name) continue

    const label = `feedback:${name}`
    try {
      execSync(
        `gh label create "${label}" --repo ${repo} --description "Feedback on the ${name} skill" --color c5def5`,
        { stdio: ['pipe', 'pipe', 'pipe'] },
      )
      result.labels.push(label)
    } catch {
      // Label likely already exists
    }
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

export function runSetup(
  root: string,
  metaDir: string,
  args: string[],
): SetupResult {
  const doAll = args.includes('--all')
  const doWorkflows = doAll || args.includes('--workflows')
  const doShim = doAll || args.includes('--shim')
  const doLabels = doAll || args.includes('--labels')

  // If no flags, default to --all
  const defaultAll = !doWorkflows && !doShim && !doLabels
  const installWorkflows = doWorkflows || defaultAll
  const installShim = doShim || defaultAll

  const vars = detectVars(root)
  const result: SetupResult = {
    workflows: [],
    skipped: [],
    shim: null,
    labels: [],
  }

  const templatesDir = join(metaDir, 'templates')

  if (installWorkflows) {
    const srcDir = join(templatesDir, 'workflows')
    const destDir = join(root, '.github', 'workflows')
    const { copied, skipped } = copyTemplates(srcDir, destDir, vars)
    result.workflows = copied
    result.skipped.push(...skipped)
  }

  if (installShim) {
    generateShim(root, result)
  }

  if (doLabels) {
    createSkillLabels(root, vars.REPO, result)
  }

  // Print results
  for (const f of result.workflows) console.log(`✓ Copied workflow: ${f}`)
  for (const f of result.skipped) console.log(`  Already exists: ${f}`)

  if (result.shim) {
    const shimRelative = result.shim.replace(root + '/', './')
    console.log(`✓ Generated intent shim: ${result.shim}`)
    console.log(`\n  Add to your package.json:`)
    console.log(`    "bin": { "intent": "${shimRelative}" }`)
    console.log(`\n  Add "bin" to your package.json "files" array.`)
  }

  if (result.labels.length > 0) {
    console.log(
      `✓ Created ${result.labels.length} feedback labels on ${vars.REPO}`,
    )
  }

  if (
    result.workflows.length === 0 &&
    result.shim === null &&
    result.labels.length === 0 &&
    result.skipped.length === 0
  ) {
    console.log('No templates directory found. Is @tanstack/intent installed?')
  } else if (result.workflows.length > 0) {
    console.log(`\nTemplate variables applied:`)
    console.log(`  Package:  ${vars.PACKAGE_NAME}`)
    console.log(`  Repo:     ${vars.REPO}`)
    console.log(`  Docs:     ${vars.DOCS_PATH}`)
    console.log(`  Src:      ${vars.SRC_PATH}`)
  }

  return result
}
